springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging.level.com.growby.library.backend: DEBUG
spring:
  application:
    name: "library-backend"
  h2:
    console:
      enabled: true
  datasource:
    initialization-mode: always  # This enables data source initialization
    url: jdbc:h2:mem:librarydb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none