DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS LOAN;

CREATE TABLE BOOK (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    author VARCHAR2(255) NOT NULL,
    isbn VARCHAR2(50) UNIQUE NOT NULL,
    publication_date DATE,
    status VARCHAR2(50) CHECK (status IN ('Disponible', 'No disponible'))
);

CREATE TABLE AUTHOR (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    nationality VARCHAR2(100),
    birth_date DATE
);

CREATE TABLE LOAN (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_date DATE NOT NULL,
    return_date DATE,
    status VARCHAR2(50) CHECK (status IN ('Activo', 'Finalizado')),
    book_id NUMBER,
    FOREIGN KEY (book_id) REFERENCES book(id)
);

-- Data for Author Table
INSERT INTO AUTHOR (name, nationality, birth_date)
VALUES ('J.K. Rowling', 'British', '1965-07-31');
INSERT INTO AUTHOR (name, nationality, birth_date)
VALUES ('George Orwell', 'British', '1903-06-25');

-- Data for Book Table
INSERT INTO BOOK (title, author, isbn, publication_date, status)
VALUES ('Harry Potter and the Sorcerer Stone', 'J.K. Rowling', '978-0439708180', '1997-06-26', 'Disponible');
INSERT INTO BOOK (title, author, isbn, publication_date, status)
VALUES ('1984', 'George Orwell', '978-0451524935', '1949-06-08', 'No disponible');

-- Data for Loan Table
INSERT INTO LOAN (loan_date, return_date, status, book_id)
VALUES ('2024-11-01', '2024-11-15', 'Activo', 1);
INSERT INTO LOAN (loan_date, return_date, status, book_id)
VALUES ('2024-11-05', '2024-11-20', 'Activo', 2);
