DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS LOAN;

CREATE TABLE AUTHOR (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL,
    NATIONALITY VARCHAR2(100),
    BIRTH_DATE DATE
);

CREATE TABLE BOOK (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TITLE VARCHAR2(255) NOT NULL,
    AUTHOR_ID NUMBER NOT NULL,
    ISBN VARCHAR2(50) UNIQUE NOT NULL,
    PUBLICATION_DATE DATE,
    STATUS VARCHAR2(50) CHECK (status IN ('Disponible', 'No disponible')),
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID)
);

CREATE TABLE LOAN (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    LOAN_DATE DATE NOT NULL,
    RETURN_DATE DATE,
    STATUS VARCHAR2(50) CHECK (status IN ('Activo', 'Finalizado')),
    BOOK_ID NUMBER,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID)
);

-- Data for Author Table
INSERT INTO AUTHOR (NAME, NATIONALITY, BIRTH_DATE)
VALUES ('J.K. Rowling', 'British', '1965-07-31');

INSERT INTO AUTHOR (NAME, NATIONALITY, BIRTH_DATE)
VALUES ('George Orwell', 'British', '1903-06-25');

INSERT INTO AUTHOR (NAME, NATIONALITY, BIRTH_DATE)
VALUES ('J.R.R. Tolkien', 'British', '1892-01-03');

INSERT INTO AUTHOR (NAME, NATIONALITY, BIRTH_DATE)
VALUES ('Leo Tolstoy', 'Russian', '1828-09-09');

-- Data for Book Table
-- 1. Harry Potter and the Sorcerer's Stone
INSERT INTO BOOK (TITLE, AUTHOR_ID, ISBN, PUBLICATION_DATE, STATUS)
VALUES ('Harry Potter and the Sorcerers Stone', 1, '978-0439708180', '1997-06-26', 'Disponible');

-- 2. 1984
INSERT INTO BOOK (TITLE, AUTHOR_ID, ISBN, PUBLICATION_DATE, STATUS)
VALUES ('1984', 2, '978-0451524935', '1949-06-08', 'No disponible');

-- 3. Harry Potter and the Chamber of Secrets
INSERT INTO BOOK (TITLE, AUTHOR_ID, ISBN, PUBLICATION_DATE, STATUS)
VALUES ('Harry Potter and the Chamber of Secrets', 1, '978-0439064873', '1998-07-02', 'Disponible');

-- 4. Animal Farm
INSERT INTO BOOK (TITLE, AUTHOR_ID, ISBN, PUBLICATION_DATE, STATUS)
VALUES ('Animal Farm', 2, '978-0451526342', '1945-08-17', 'No disponible');

-- 5. Harry Potter and the Prisoner of Azkaban
INSERT INTO BOOK (TITLE, AUTHOR_ID, ISBN, PUBLICATION_DATE, STATUS)
VALUES ('Harry Potter and the Prisoner of Azkaban', 1, '978-0439136358', '1999-07-08', 'Disponible');

-- 6. Homage to Catalonia
INSERT INTO BOOK (TITLE, AUTHOR_ID, ISBN, PUBLICATION_DATE, STATUS)
VALUES ('Homage to Catalonia', 2, '978-0156421171', '1938-04-20', 'No disponible');

-- 7. Harry Potter and the Goblet of Fire
INSERT INTO BOOK (TITLE, AUTHOR_ID, ISBN, PUBLICATION_DATE, STATUS)
VALUES ('Harry Potter and the Goblet of Fire', 1, '978-0439139601', '2000-07-08', 'Disponible');

-- 8. Down and Out in Paris and London
INSERT INTO BOOK (TITLE, AUTHOR_ID, ISBN, PUBLICATION_DATE, STATUS)
VALUES ('Down and Out in Paris and London', 2, '978-0156262248', '1933-01-01', 'No disponible');

-- 9. Harry Potter and the Order of the Phoenix
INSERT INTO BOOK (TITLE, AUTHOR_ID, ISBN, PUBLICATION_DATE, STATUS)
VALUES ('Harry Potter and the Order of the Phoenix', 1, '978-0439358071', '2003-06-21', 'Disponible');

-- 10. The Road to Wigan Pier
INSERT INTO BOOK (TITLE, AUTHOR_ID, ISBN, PUBLICATION_DATE, STATUS)
VALUES ('The Road to Wigan Pier', 2, '978-0156767505', '1937-03-01', 'No disponible');

-- 11. Harry Potter and the Half-Blood Prince
INSERT INTO BOOK (TITLE, AUTHOR_ID, ISBN, PUBLICATION_DATE, STATUS)
VALUES ('Harry Potter and the Half-Blood Prince', 1, '978-0439785969', '2005-07-16', 'Disponible');

-- 12. The Lord of the Rings: The Fellowship of the Ring
INSERT INTO BOOK (TITLE, AUTHOR_ID, ISBN, PUBLICATION_DATE, STATUS)
VALUES ('The Lord of the Rings: The Fellowship of the Ring', 3, '978-0618574940', '1954-07-29', 'Disponible');

-- Data for Loan Table
-- 1. Loan for Harry Potter and the Sorcerer's Stone
INSERT INTO LOAN (LOAN_DATE, RETURN_DATE, STATUS, BOOK_ID)
VALUES ('2024-11-01', '2024-12-15', 'Finalizado', 1);

-- 2. Loan for 1984
INSERT INTO LOAN (LOAN_DATE, RETURN_DATE, STATUS, BOOK_ID)
VALUES ('2024-11-05', '2024-12-20', 'Activo', 2);

-- 3. Loan for Harry Potter and the Chamber of Secrets
INSERT INTO LOAN (LOAN_DATE, RETURN_DATE, STATUS, BOOK_ID)
VALUES ('2024-11-10', '2024-12-10', 'Finalizado', 3);

-- 4. Loan for Animal Farm
INSERT INTO LOAN (LOAN_DATE, RETURN_DATE, STATUS, BOOK_ID)
VALUES ('2024-11-12', '2024-11-26', 'Finalizado', 4);

-- 5. Loan for Harry Potter and the Prisoner of Azkaban
INSERT INTO LOAN (LOAN_DATE, RETURN_DATE, STATUS, BOOK_ID)
VALUES ('2024-11-15', '2024-12-15', 'Finalizado', 5);

-- 6. Loan for Homage to Catalonia
INSERT INTO LOAN (LOAN_DATE, RETURN_DATE, STATUS, BOOK_ID)
VALUES ('2024-11-17', '2024-12-01', 'Finalizado', 6);

-- 7. Loan for Harry Potter and the Goblet of Fire
INSERT INTO LOAN (LOAN_DATE, RETURN_DATE, STATUS, BOOK_ID)
VALUES ('2024-11-20', '2024-12-10', 'Finalizado', 7);

-- 8. Loan for The Lord of the Rings: The Fellowship of the Ring
INSERT INTO LOAN (LOAN_DATE, RETURN_DATE, STATUS, BOOK_ID)
VALUES ('2024-11-22', '2024-12-22', 'Activo', 12);

